apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sachin-deploy
spec:
  replicas: 3
  selector:
    matchLabels:  
      app: blue 
  template:
    metadata: 
      name: my-template
      labels: 
        app: blue 
    spec: 
      containers:
      - name: sachin-cont003
        image: rathodsr/blue
        ports:
        - containerPort: 80
