apiVersion: v1
kind: ReplicationController
metadata: 
  name: replication-controller

spec:
  replicas: 3
  selector:
    env: dev
  template:
    metadata:
      name: netflix
      labels:
        env: dev
    spec:
      containers:
        - name: cont-01
          image: rathodsr/netflix
          ports:
            - containerPort: 80
